CREATE SEQUENCE CUSTOMERS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER CUSTOMERS_TRG
BEFORE INSERT ON CUSTOMERS
FOR EACH ROW
BEGIN
  IF :NEW.CUSTOMER_ID IS NULL THEN
    SELECT CUSTOMERS_SEQ.NEXTVAL INTO :NEW.CUSTOMER_ID FROM DUAL;
  END IF;
END;

